services:
  postgres:
    container_name: postgres_myapp
    image: timescale/timescaledb:latest-pg15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mailpit:
    container_name: mailpit_app
    image: axllent/mailpit
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    restart: always

  prisma-studio:
    container_name: prisma-studio_app
    image: timothyjmiller/prisma-studio:latest
    restart: always
    environment:
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5433/postgres
    ports:
      - 5556:5555

volumes:
  db_data: {}
  tempo-data: {}
